# Generated by Django 5.1.3 on 2025-01-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommece_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
